# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 600)
        Dialog.setMinimumSize(QtCore.QSize(400, 600))
        Dialog.setMaximumSize(QtCore.QSize(400, 600))
        Dialog.setBaseSize(QtCore.QSize(400, 600))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.saveBtn = QtWidgets.QPushButton(self.tab)
        self.saveBtn.setGeometry(QtCore.QRect(10, 540, 371, 31))
        self.saveBtn.setObjectName("saveBtn")
        self.searchBtn = QtWidgets.QPushButton(self.tab)
        self.searchBtn.setGeometry(QtCore.QRect(330, 9, 51, 33))
        self.searchBtn.setMaximumSize(QtCore.QSize(16777215, 33))
        self.searchBtn.setObjectName("searchBtn")
        self.LocationBox = QtWidgets.QComboBox(self.tab)
        self.LocationBox.setGeometry(QtCore.QRect(10, 10, 311, 31))
        self.LocationBox.setCurrentText("")
        self.LocationBox.setObjectName("LocationBox")
        self.LocationList = QtWidgets.QListWidget(self.tab)
        self.LocationList.setGeometry(QtCore.QRect(10, 50, 371, 251))
        self.LocationList.setMaximumSize(QtCore.QSize(371, 491))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LocationList.setFont(font)
        self.LocationList.setObjectName("LocationList")
        self.DetailList = QtWidgets.QListWidget(self.tab)
        self.DetailList.setGeometry(QtCore.QRect(10, 300, 371, 241))
        self.DetailList.setMaximumSize(QtCore.QSize(371, 491))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DetailList.setFont(font)
        self.DetailList.setObjectName("DetailList")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Loaction = QtWidgets.QLabel(self.tab_2)
        self.Loaction.setGeometry(QtCore.QRect(32, 9, 361, 31))
        self.Loaction.setMaximumSize(QtCore.QSize(361, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Loaction.setFont(font)
        self.Loaction.setAutoFillBackground(False)
        self.Loaction.setScaledContents(False)
        self.Loaction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Loaction.setObjectName("Loaction")
        self.getTime = QtWidgets.QLabel(self.tab_2)
        self.getTime.setGeometry(QtCore.QRect(210, 40, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.getTime.setFont(font)
        self.getTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.getTime.setObjectName("getTime")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 371, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.fore_icon = QtWidgets.QLabel(self.groupBox)
        self.fore_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.fore_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.fore_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.fore_icon.setObjectName("fore_icon")
        self.totalLabel = QtWidgets.QLabel(self.groupBox)
        self.totalLabel.setGeometry(QtCore.QRect(190, 10, 171, 81))
        self.totalLabel.setMaximumSize(QtCore.QSize(171, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.totalLabel.setFont(font)
        self.totalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalLabel.setObjectName("totalLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 371, 101))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.dust_icon = QtWidgets.QLabel(self.groupBox_2)
        self.dust_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.dust_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.dust_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_icon.setObjectName("dust_icon")
        self.pm10Label = QtWidgets.QLabel(self.groupBox_2)
        self.pm10Label.setGeometry(QtCore.QRect(190, 10, 171, 81))
        self.pm10Label.setMaximumSize(QtCore.QSize(171, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.pm10Label.setFont(font)
        self.pm10Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pm10Label.setObjectName("pm10Label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 371, 101))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.o3Label = QtWidgets.QLabel(self.groupBox_3)
        self.o3Label.setGeometry(QtCore.QRect(10, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o3Label.setFont(font)
        self.o3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.o3Label.setObjectName("o3Label")
        self.No2Label = QtWidgets.QLabel(self.groupBox_3)
        self.No2Label.setGeometry(QtCore.QRect(80, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.No2Label.setFont(font)
        self.No2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.No2Label.setObjectName("No2Label")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(80, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(80, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.CoLabel = QtWidgets.QLabel(self.groupBox_3)
        self.CoLabel.setGeometry(QtCore.QRect(180, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CoLabel.setFont(font)
        self.CoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CoLabel.setObjectName("CoLabel")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(180, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(180, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.So2Label = QtWidgets.QLabel(self.groupBox_3)
        self.So2Label.setGeometry(QtCore.QRect(280, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.So2Label.setFont(font)
        self.So2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.So2Label.setObjectName("So2Label")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(280, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(280, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 400, 371, 71))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.stateImg = QtWidgets.QLabel(self.tab_2)
        self.stateImg.setGeometry(QtCore.QRect(10, 500, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stateImg.setFont(font)
        self.stateImg.setAlignment(QtCore.Qt.AlignCenter)
        self.stateImg.setObjectName("stateImg")
        self.GPSImage = QtWidgets.QLabel(self.tab_2)
        self.GPSImage.setGeometry(QtCore.QRect(3, 10, 31, 31))
        self.GPSImage.setMaximumSize(QtCore.QSize(31, 31))
        self.GPSImage.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSImage.setObjectName("GPSImage")
        self.refreshBtn = QtWidgets.QPushButton(self.tab_2)
        self.refreshBtn.setGeometry(QtCore.QRect(350, 10, 31, 31))
        self.refreshBtn.setObjectName("refreshBtn")
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.Loaction.raise_()
        self.getTime.raise_()
        self.groupBox.raise_()
        self.groupBox_4.raise_()
        self.stateImg.raise_()
        self.GPSImage.raise_()
        self.refreshBtn.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "미세먼지 주의보"))
        self.saveBtn.setAccessibleName(_translate("Dialog", "saveBtn"))
        self.saveBtn.setText(_translate("Dialog", "저장"))
        self.searchBtn.setAccessibleName(_translate("Dialog", "searchBtn"))
        self.searchBtn.setText(_translate("Dialog", "검색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "지역 검색"))
        self.Loaction.setText(_translate("Dialog", "내 위치가 표시 된다."))
        self.getTime.setText(_translate("Dialog", "측정 시간 : 2016-06-16 00:00"))
        self.fore_icon.setText(_translate("Dialog", "fore_Img"))
        self.totalLabel.setText(_translate("Dialog", "000"))
        self.dust_icon.setText(_translate("Dialog", "dust_Img"))
        self.pm10Label.setText(_translate("Dialog", "000"))
        self.label.setText(_translate("Dialog", "O3"))
        self.label_2.setText(_translate("Dialog", "오존"))
        self.o3Label.setText(_translate("Dialog", "0.0000"))
        self.No2Label.setText(_translate("Dialog", "0.0000"))
        self.label_5.setText(_translate("Dialog", "NO2"))
        self.label_6.setText(_translate("Dialog", "이산화질소"))
        self.CoLabel.setText(_translate("Dialog", "0.0000"))
        self.label_8.setText(_translate("Dialog", "CO"))
        self.label_9.setText(_translate("Dialog", "일산화탄소"))
        self.So2Label.setText(_translate("Dialog", "0.0000"))
        self.label_11.setText(_translate("Dialog", "SO2"))
        self.label_12.setText(_translate("Dialog", "이황산가스"))
        self.stateImg.setText(_translate("Dialog", "상태를 나타내는 이미지"))
        self.GPSImage.setText(_translate("Dialog", "img"))
        self.refreshBtn.setText(_translate("Dialog", "갱신"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "오염 정보"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "준비3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "준비4"))

