# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 600)
        Dialog.setMinimumSize(QtCore.QSize(400, 600))
        Dialog.setMaximumSize(QtCore.QSize(400, 600))
        Dialog.setBaseSize(QtCore.QSize(400, 600))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.LocationList = QtWidgets.QListView(self.tab)
        self.LocationList.setGeometry(QtCore.QRect(10, 50, 371, 491))
        self.LocationList.setObjectName("LocationList")
        self.saveBtn = QtWidgets.QPushButton(self.tab)
        self.saveBtn.setGeometry(QtCore.QRect(10, 540, 371, 31))
        self.saveBtn.setObjectName("saveBtn")
        self.searchBtn = QtWidgets.QPushButton(self.tab)
        self.searchBtn.setGeometry(QtCore.QRect(330, 9, 51, 33))
        self.searchBtn.setMaximumSize(QtCore.QSize(16777215, 33))
        self.searchBtn.setObjectName("searchBtn")
        self.LocationBox = QtWidgets.QComboBox(self.tab)
        self.LocationBox.setGeometry(QtCore.QRect(10, 10, 311, 31))
        self.LocationBox.setCurrentText("")
        self.LocationBox.setObjectName("LocationBox")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Loaction = QtWidgets.QLabel(self.tab_2)
        self.Loaction.setGeometry(QtCore.QRect(30, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Loaction.setFont(font)
        self.Loaction.setAutoFillBackground(False)
        self.Loaction.setScaledContents(False)
        self.Loaction.setAlignment(QtCore.Qt.AlignCenter)
        self.Loaction.setObjectName("Loaction")
        self.getTime = QtWidgets.QLabel(self.tab_2)
        self.getTime.setGeometry(QtCore.QRect(130, 18, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.getTime.setFont(font)
        self.getTime.setAlignment(QtCore.Qt.AlignCenter)
        self.getTime.setObjectName("getTime")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 371, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.fore_icon = QtWidgets.QLabel(self.groupBox)
        self.fore_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.fore_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.fore_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.fore_icon.setObjectName("fore_icon")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 371, 101))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.dust_icon = QtWidgets.QLabel(self.groupBox_2)
        self.dust_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.dust_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.dust_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_icon.setObjectName("dust_icon")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 371, 121))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 420, 371, 71))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.stateImg = QtWidgets.QLabel(self.tab_2)
        self.stateImg.setGeometry(QtCore.QRect(10, 500, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stateImg.setFont(font)
        self.stateImg.setAlignment(QtCore.Qt.AlignCenter)
        self.stateImg.setObjectName("stateImg")
        self.GPSImage = QtWidgets.QLabel(self.tab_2)
        self.GPSImage.setGeometry(QtCore.QRect(3, 10, 31, 31))
        self.GPSImage.setMaximumSize(QtCore.QSize(31, 31))
        self.GPSImage.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSImage.setObjectName("GPSImage")
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.Loaction.raise_()
        self.getTime.raise_()
        self.groupBox.raise_()
        self.groupBox_4.raise_()
        self.stateImg.raise_()
        self.GPSImage.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "미세먼지 주의보"))
        self.saveBtn.setText(_translate("Dialog", "저장"))
        self.searchBtn.setText(_translate("Dialog", "검색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "지역 검색"))
        self.Loaction.setText(_translate("Dialog", "정왕동"))
        self.getTime.setText(_translate("Dialog", "측정 시간 : 2016년 05월 13일 10시 00분"))
        self.fore_icon.setText(_translate("Dialog", "fore_Img"))
        self.dust_icon.setText(_translate("Dialog", "dust_Img"))
        self.stateImg.setText(_translate("Dialog", "상태를 나타내는 이미지"))
        self.GPSImage.setText(_translate("Dialog", "img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "오염 정보"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "준비3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "준비4"))  

