# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 600)
        Dialog.setMinimumSize(QtCore.QSize(400, 600))
        Dialog.setMaximumSize(QtCore.QSize(400, 600))
        Dialog.setBaseSize(QtCore.QSize(400, 600))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 601))
        self.tabWidget.setMaximumSize(QtCore.QSize(401, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.saveBtn = QtWidgets.QPushButton(self.tab)
        self.saveBtn.setGeometry(QtCore.QRect(10, 540, 371, 31))
        self.saveBtn.setObjectName("saveBtn")
        self.searchBtn = QtWidgets.QPushButton(self.tab)
        self.searchBtn.setGeometry(QtCore.QRect(250, 9, 61, 33))
        self.searchBtn.setMaximumSize(QtCore.QSize(16777215, 33))
        self.searchBtn.setObjectName("searchBtn")
        self.LocationBox = QtWidgets.QComboBox(self.tab)
        self.LocationBox.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.LocationBox.setCurrentText("")
        self.LocationBox.setObjectName("LocationBox")
        self.LocationList = QtWidgets.QListWidget(self.tab)
        self.LocationList.setGeometry(QtCore.QRect(10, 50, 371, 251))
        self.LocationList.setMaximumSize(QtCore.QSize(371, 491))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LocationList.setFont(font)
        self.LocationList.setObjectName("LocationList")
        self.DetailList = QtWidgets.QListWidget(self.tab)
        self.DetailList.setGeometry(QtCore.QRect(10, 300, 371, 241))
        self.DetailList.setMaximumSize(QtCore.QSize(371, 491))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DetailList.setFont(font)
        self.DetailList.setObjectName("DetailList")
        self.searchBtn_2 = QtWidgets.QPushButton(self.tab)
        self.searchBtn_2.setGeometry(QtCore.QRect(320, 9, 61, 33))
        self.searchBtn_2.setMaximumSize(QtCore.QSize(16777215, 33))
        self.searchBtn_2.setObjectName("searchBtn_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Loaction = QtWidgets.QLabel(self.tab_2)
        self.Loaction.setGeometry(QtCore.QRect(32, 9, 361, 31))
        self.Loaction.setMaximumSize(QtCore.QSize(361, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Loaction.setFont(font)
        self.Loaction.setAutoFillBackground(False)
        self.Loaction.setScaledContents(False)
        self.Loaction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Loaction.setObjectName("Loaction")
        self.getTime = QtWidgets.QLabel(self.tab_2)
        self.getTime.setGeometry(QtCore.QRect(210, 40, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.getTime.setFont(font)
        self.getTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.getTime.setObjectName("getTime")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 371, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.fore_icon = QtWidgets.QLabel(self.groupBox)
        self.fore_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.fore_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.fore_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.fore_icon.setObjectName("fore_icon")
        self.totalLabel = QtWidgets.QLabel(self.groupBox)
        self.totalLabel.setGeometry(QtCore.QRect(190, 10, 171, 81))
        self.totalLabel.setMaximumSize(QtCore.QSize(171, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.totalLabel.setFont(font)
        self.totalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalLabel.setObjectName("totalLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 371, 101))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.dust_icon = QtWidgets.QLabel(self.groupBox_2)
        self.dust_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.dust_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.dust_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.dust_icon.setObjectName("dust_icon")
        self.pm10Label = QtWidgets.QLabel(self.groupBox_2)
        self.pm10Label.setGeometry(QtCore.QRect(190, 10, 171, 81))
        self.pm10Label.setMaximumSize(QtCore.QSize(171, 81))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.pm10Label.setFont(font)
        self.pm10Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pm10Label.setObjectName("pm10Label")
        self.pm10_1hLabel = QtWidgets.QLabel(self.groupBox_2)
        self.pm10_1hLabel.setGeometry(QtCore.QRect(10, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pm10_1hLabel.setFont(font)
        self.pm10_1hLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pm10_1hLabel.setObjectName("pm10_1hLabel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 371, 101))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.o3Label = QtWidgets.QLabel(self.groupBox_3)
        self.o3Label.setGeometry(QtCore.QRect(10, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o3Label.setFont(font)
        self.o3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.o3Label.setObjectName("o3Label")
        self.No2Label = QtWidgets.QLabel(self.groupBox_3)
        self.No2Label.setGeometry(QtCore.QRect(80, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.No2Label.setFont(font)
        self.No2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.No2Label.setObjectName("No2Label")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(80, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(80, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.CoLabel = QtWidgets.QLabel(self.groupBox_3)
        self.CoLabel.setGeometry(QtCore.QRect(180, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CoLabel.setFont(font)
        self.CoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CoLabel.setObjectName("CoLabel")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(180, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(180, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.So2Label = QtWidgets.QLabel(self.groupBox_3)
        self.So2Label.setGeometry(QtCore.QRect(280, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.So2Label.setFont(font)
        self.So2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.So2Label.setObjectName("So2Label")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(280, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(280, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 400, 371, 71))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.stateImg = QtWidgets.QLabel(self.tab_2)
        self.stateImg.setGeometry(QtCore.QRect(10, 500, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stateImg.setFont(font)
        self.stateImg.setAlignment(QtCore.Qt.AlignCenter)
        self.stateImg.setObjectName("stateImg")
        self.GPSImage = QtWidgets.QLabel(self.tab_2)
        self.GPSImage.setGeometry(QtCore.QRect(3, 10, 31, 31))
        self.GPSImage.setMaximumSize(QtCore.QSize(31, 31))
        self.GPSImage.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSImage.setObjectName("GPSImage")
        self.refreshBtn = QtWidgets.QPushButton(self.tab_2)
        self.refreshBtn.setGeometry(QtCore.QRect(350, 10, 31, 31))
        self.refreshBtn.setObjectName("refreshBtn")
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.Loaction.raise_()
        self.getTime.raise_()
        self.groupBox.raise_()
        self.groupBox_4.raise_()
        self.stateImg.raise_()
        self.GPSImage.raise_()
        self.refreshBtn.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pm10_img = QtWidgets.QLabel(self.tab_3)
        self.pm10_img.setGeometry(QtCore.QRect(10, 10, 381, 301))
        self.pm10_img.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pm10_img.setAutoFillBackground(False)
        self.pm10_img.setAlignment(QtCore.Qt.AlignCenter)
        self.pm10_img.setObjectName("pm10_img")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(10, 350, 381, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(10, 310, 381, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.today = QtWidgets.QLabel(self.tab_3)
        self.today.setGeometry(QtCore.QRect(10, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.today.setFont(font)
        self.today.setObjectName("today")
        self.today_date = QtWidgets.QLabel(self.tab_3)
        self.today_date.setGeometry(QtCore.QRect(95, 335, 121, 16))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setBold(True)
        font.setWeight(75)
        self.today_date.setFont(font)
        self.today_date.setObjectName("today_date")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 370, 61, 16))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(10, 410, 381, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 430, 61, 16))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setGeometry(QtCore.QRect(10, 480, 381, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 500, 61, 16))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.informGrade = QtWidgets.QPlainTextEdit(self.tab_3)
        self.informGrade.setEnabled(True)
        self.informGrade.setGeometry(QtCore.QRect(20, 520, 361, 51))
        self.informGrade.setMaximumSize(QtCore.QSize(361, 51))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setBold(True)
        font.setWeight(75)
        self.informGrade.setFont(font)
        self.informGrade.setAutoFillBackground(False)
        self.informGrade.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.informGrade.setFrameShadow(QtWidgets.QFrame.Plain)
        self.informGrade.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informGrade.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informGrade.setDocumentTitle("")
        self.informGrade.setPlainText("")
        self.informGrade.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.informGrade.setBackgroundVisible(True)
        self.informGrade.setObjectName("informGrade")
        self.informCause = QtWidgets.QPlainTextEdit(self.tab_3)
        self.informCause.setEnabled(True)
        self.informCause.setGeometry(QtCore.QRect(20, 450, 361, 31))
        self.informCause.setMaximumSize(QtCore.QSize(361, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setBold(True)
        font.setWeight(75)
        self.informCause.setFont(font)
        self.informCause.setAutoFillBackground(False)
        self.informCause.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.informCause.setFrameShadow(QtWidgets.QFrame.Plain)
        self.informCause.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informCause.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informCause.setDocumentTitle("")
        self.informCause.setPlainText("")
        self.informCause.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.informCause.setBackgroundVisible(True)
        self.informCause.setObjectName("informCause")
        self.refreshBtn_2 = QtWidgets.QPushButton(self.tab_3)
        self.refreshBtn_2.setGeometry(QtCore.QRect(331, 330, 51, 21))
        self.refreshBtn_2.setObjectName("refreshBtn_2")
        self.informOverall = QtWidgets.QPlainTextEdit(self.tab_3)
        self.informOverall.setEnabled(True)
        self.informOverall.setGeometry(QtCore.QRect(20, 390, 361, 21))
        self.informOverall.setMaximumSize(QtCore.QSize(361, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setBold(True)
        font.setWeight(75)
        self.informOverall.setFont(font)
        self.informOverall.setAutoFillBackground(False)
        self.informOverall.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.informOverall.setFrameShadow(QtWidgets.QFrame.Plain)
        self.informOverall.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informOverall.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informOverall.setDocumentTitle("")
        self.informOverall.setPlainText("")
        self.informOverall.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.informOverall.setBackgroundVisible(True)
        self.informOverall.setObjectName("informOverall")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.getTime_2 = QtWidgets.QLabel(self.tab_4)
        self.getTime_2.setGeometry(QtCore.QRect(10, 70, 371, 21))
        self.getTime_2.setMaximumSize(QtCore.QSize(371, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.getTime_2.setFont(font)
        self.getTime_2.setAlignment(QtCore.Qt.AlignCenter)
        self.getTime_2.setObjectName("getTime_2")
        self.emoIcon = QtWidgets.QLabel(self.tab_4)
        self.emoIcon.setGeometry(QtCore.QRect(10, 120, 371, 127))
        self.emoIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.emoIcon.setAutoFillBackground(True)
        self.emoIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.emoIcon.setObjectName("emoIcon")
        self.Loaction_2 = QtWidgets.QLabel(self.tab_4)
        self.Loaction_2.setGeometry(QtCore.QRect(10, 20, 371, 31))
        self.Loaction_2.setMaximumSize(QtCore.QSize(371, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Loaction_2.setFont(font)
        self.Loaction_2.setAutoFillBackground(False)
        self.Loaction_2.setScaledContents(False)
        self.Loaction_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Loaction_2.setObjectName("Loaction_2")
        self.NowState = QtWidgets.QLabel(self.tab_4)
        self.NowState.setGeometry(QtCore.QRect(10, 270, 371, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(24)
        self.NowState.setFont(font)
        self.NowState.setAlignment(QtCore.Qt.AlignCenter)
        self.NowState.setObjectName("NowState")
        self.totalValue = QtWidgets.QLabel(self.tab_4)
        self.totalValue.setGeometry(QtCore.QRect(10, 340, 371, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.totalValue.setFont(font)
        self.totalValue.setAlignment(QtCore.Qt.AlignCenter)
        self.totalValue.setObjectName("totalValue")
        self.line_5 = QtWidgets.QFrame(self.tab_4)
        self.line_5.setGeometry(QtCore.QRect(10, 370, 381, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.PM10Label_2 = QtWidgets.QLabel(self.tab_4)
        self.PM10Label_2.setGeometry(QtCore.QRect(0, 510, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PM10Label_2.setFont(font)
        self.PM10Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.PM10Label_2.setObjectName("PM10Label_2")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(0, 390, 71, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.emoIcon_2 = QtWidgets.QLabel(self.tab_4)
        self.emoIcon_2.setGeometry(QtCore.QRect(0, 440, 71, 61))
        self.emoIcon_2.setMaximumSize(QtCore.QSize(127, 127))
        self.emoIcon_2.setAutoFillBackground(True)
        self.emoIcon_2.setAlignment(QtCore.Qt.AlignCenter)
        self.emoIcon_2.setObjectName("emoIcon_2")
        self.line_6 = QtWidgets.QFrame(self.tab_4)
        self.line_6.setGeometry(QtCore.QRect(10, 530, 381, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(80, 390, 71, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.emoIcon_3 = QtWidgets.QLabel(self.tab_4)
        self.emoIcon_3.setGeometry(QtCore.QRect(80, 440, 71, 61))
        self.emoIcon_3.setMaximumSize(QtCore.QSize(127, 127))
        self.emoIcon_3.setAutoFillBackground(True)
        self.emoIcon_3.setAlignment(QtCore.Qt.AlignCenter)
        self.emoIcon_3.setObjectName("emoIcon_3")
        self.o3Label_2 = QtWidgets.QLabel(self.tab_4)
        self.o3Label_2.setGeometry(QtCore.QRect(80, 510, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.o3Label_2.setFont(font)
        self.o3Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.o3Label_2.setObjectName("o3Label_2")
        self.emoIcon_4 = QtWidgets.QLabel(self.tab_4)
        self.emoIcon_4.setGeometry(QtCore.QRect(160, 440, 71, 61))
        self.emoIcon_4.setMaximumSize(QtCore.QSize(127, 127))
        self.emoIcon_4.setAutoFillBackground(True)
        self.emoIcon_4.setAlignment(QtCore.Qt.AlignCenter)
        self.emoIcon_4.setObjectName("emoIcon_4")
        self.No2Label_2 = QtWidgets.QLabel(self.tab_4)
        self.No2Label_2.setGeometry(QtCore.QRect(160, 510, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.No2Label_2.setFont(font)
        self.No2Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.No2Label_2.setObjectName("No2Label_2")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(160, 390, 71, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.emoIcon_5 = QtWidgets.QLabel(self.tab_4)
        self.emoIcon_5.setGeometry(QtCore.QRect(240, 440, 71, 61))
        self.emoIcon_5.setMaximumSize(QtCore.QSize(127, 127))
        self.emoIcon_5.setAutoFillBackground(True)
        self.emoIcon_5.setAlignment(QtCore.Qt.AlignCenter)
        self.emoIcon_5.setObjectName("emoIcon_5")
        self.CoLabel_2 = QtWidgets.QLabel(self.tab_4)
        self.CoLabel_2.setGeometry(QtCore.QRect(240, 510, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CoLabel_2.setFont(font)
        self.CoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.CoLabel_2.setObjectName("CoLabel_2")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(240, 390, 71, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.So2Label_2 = QtWidgets.QLabel(self.tab_4)
        self.So2Label_2.setGeometry(QtCore.QRect(320, 510, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.So2Label_2.setFont(font)
        self.So2Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.So2Label_2.setObjectName("So2Label_2")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(320, 390, 71, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.emoIcon_6 = QtWidgets.QLabel(self.tab_4)
        self.emoIcon_6.setGeometry(QtCore.QRect(320, 440, 71, 61))
        self.emoIcon_6.setMaximumSize(QtCore.QSize(127, 127))
        self.emoIcon_6.setAutoFillBackground(True)
        self.emoIcon_6.setAlignment(QtCore.Qt.AlignCenter)
        self.emoIcon_6.setObjectName("emoIcon_6")
        self.refreshBtn_3 = QtWidgets.QPushButton(self.tab_4)
        self.refreshBtn_3.setGeometry(QtCore.QRect(360, 545, 31, 26))
        self.refreshBtn_3.setObjectName("refreshBtn_3")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "미세먼지 주의보"))
        self.saveBtn.setAccessibleName(_translate("Dialog", "saveBtn"))
        self.saveBtn.setText(_translate("Dialog", "저장"))
        self.searchBtn.setAccessibleName(_translate("Dialog", "searchBtn"))
        self.searchBtn.setText(_translate("Dialog", "지역 검색"))
        self.searchBtn_2.setAccessibleName(_translate("Dialog", "searchBtn"))
        self.searchBtn_2.setText(_translate("Dialog", "시도 검색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "지역 검색"))
        self.Loaction.setText(_translate("Dialog", "내 위치가 표시 된다."))
        self.getTime.setText(_translate("Dialog", "측정 시간 : 2016-06-16 00:00"))
        self.fore_icon.setText(_translate("Dialog", "fore_Img"))
        self.totalLabel.setText(_translate("Dialog", "000"))
        self.dust_icon.setText(_translate("Dialog", "dust_Img"))
        self.pm10Label.setText(_translate("Dialog", "000"))
        self.pm10_1hLabel.setText(_translate("Dialog", "시간당 : 0.000"))
        self.label.setText(_translate("Dialog", "O3"))
        self.label_2.setText(_translate("Dialog", "오존"))
        self.o3Label.setText(_translate("Dialog", "0.0000"))
        self.No2Label.setText(_translate("Dialog", "0.0000"))
        self.label_5.setText(_translate("Dialog", "NO2"))
        self.label_6.setText(_translate("Dialog", "이산화질소"))
        self.CoLabel.setText(_translate("Dialog", "0.0000"))
        self.label_8.setText(_translate("Dialog", "CO"))
        self.label_9.setText(_translate("Dialog", "일산화탄소"))
        self.So2Label.setText(_translate("Dialog", "0.0000"))
        self.label_11.setText(_translate("Dialog", "SO2"))
        self.label_12.setText(_translate("Dialog", "이황산가스"))
        self.stateImg.setText(_translate("Dialog", "상태를 나타내는 이미지"))
        self.GPSImage.setText(_translate("Dialog", "img"))
        self.refreshBtn.setText(_translate("Dialog", "갱신"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "오염 정보"))
        self.pm10_img.setText(_translate("Dialog", "pm10_Img"))
        self.today.setText(_translate("Dialog", "오늘 예보"))
        self.today_date.setText(_translate("Dialog", "2016-00-00 00시 발표"))
        self.label_3.setText(_translate("Dialog", "예보 개황"))
        self.label_4.setText(_translate("Dialog", "발생 원인"))
        self.label_7.setText(_translate("Dialog", "예보 등급"))
        self.refreshBtn_2.setText(_translate("Dialog", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "미세먼지(PM10)"))
        self.getTime_2.setText(_translate("Dialog", "측정 시간 : 2016-06-16 00:00"))
        self.emoIcon.setText(_translate("Dialog", "emoIcon"))
        self.Loaction_2.setText(_translate("Dialog", "내 위치가 표시 된다"))
        self.NowState.setText(_translate("Dialog", "현재 상태"))
        self.totalValue.setText(_translate("Dialog", "통합지수 : 30"))
        self.PM10Label_2.setText(_translate("Dialog", "0.0000"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body>PM10</br><br>미세먼지</br></body></html>"))
        self.emoIcon_2.setText(_translate("Dialog", "emoIcon"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body>O3<br>오존</br></body></html>"))
        self.emoIcon_3.setText(_translate("Dialog", "emoIcon"))
        self.o3Label_2.setText(_translate("Dialog", "0.0000"))
        self.emoIcon_4.setText(_translate("Dialog", "emoIcon"))
        self.No2Label_2.setText(_translate("Dialog", "0.0000"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body>NO2<br>이산화질소</br></body></html>"))
        self.emoIcon_5.setText(_translate("Dialog", "emoIcon"))
        self.CoLabel_2.setText(_translate("Dialog", "0.0000"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body>CO<br>일산화탄소</br></body></html>"))
        self.So2Label_2.setText(_translate("Dialog", "0.0000"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body>SO2<br>이황산가스</br></body></html>"))
        self.emoIcon_6.setText(_translate("Dialog", "emoIcon"))
        self.refreshBtn_3.setText(_translate("Dialog", "갱신"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "오염 정보(New UI)"))

